# Generated by Django 5.1.6 on 2025-03-02 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FruitPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('fruit_name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('unit', models.CharField(choices=[('kgs', 'Kilograms'), ('units', 'Units'), ('dozens', 'Dozens')], default='kgs', max_length=6)),
            ],
        ),
    ]
