# Generated by Django 5.1.6 on 2025-03-03 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruitprice',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='fruitprice',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kg'), ('box', 'Box'), ('piece', 'Piece')], default='kg', max_length=6),
        ),
        migrations.AlterUniqueTogether(
            name='fruitprice',
            unique_together={('date', 'fruit_name')},
        ),
    ]
